projetovendas/appvendas/urls.py
from django.conf.urls import patterns,include,url
from appvendas.views import *
urlpatterns=[
    url(r'^$',home,name='home'),
    url(r'^produtos/$',listarprodutos,name='produtos'),
    url(r'^produtos/exibir/(\d+)',exibirproduto,name='exibirproduto'),
    url(r'^unidades/$',listarunidades,name='unidades'),
    url(r'^unidades/exibir/(\d+)', exibirunidade, name='exibirunidade'),
    url(r'^vendas/$',listarvendas,name='vendas'),

]

projetovendas/projetovendas/urls.py
from django.conf.urls import patterns,include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^appvendas/',include('appvendas.urls'))
]

projetovendas/appvendas/models.py
from django.db import models

# Create your models here.

class Unidade(models.Model):
    descricao=models.CharField("Descrição",max_length=100)
    sigla=models.CharField("Sigla",max_length=5)
    def __str__(self):
        return "{0:s}-{1:s}".format(self.descricao,self.sigla)

class Cargo(models.Model):
    descricao=models.CharField("Descrição",max_length=150)
    def __str__(self):
        return self.descricao

class Pessoa(models.Model):
    nome=models.CharField("Nome",max_length=255)
    email=models.EmailField("E-Mail",max_length=200)
    telefone=models.CharField("Telefone",max_length=20)

    def __str__(self):
        return self.nome

class Cliente(Pessoa):
    endereco=models.CharField("Endereço",max_length=255)


class Funcionario(Pessoa):
    matricula=models.CharField("Matrícula",max_length=10,unique=True)
    cargo=models.ForeignKey(Cargo,on_delete=models.PROTECT,verbose_name="Cargo")

class Produto(models.Model):
    descricao=models.CharField("Descrição",max_length=255)
    valorUnitario=models.DecimalField("Valor Unitário",max_digits=10,decimal_places=2)
    unidade=models.ForeignKey(Unidade,on_delete=models.PROTECT,verbose_name="Unidade")

    def __str__(self):
        return self.descricao

class Venda(models.Model):
    dataVenda=models.DateField("Data da Venda")
    vendedor=models.ForeignKey(Funcionario,on_delete=models.PROTECT,verbose_name="Funcionário")
    cliente=models.ForeignKey(Cliente,on_delete=models.PROTECT,verbose_name="Cliente")
    produtos=models.ManyToManyField(Produto,through="VendaProduto")

    def __str__(self):
        return "{0:d}-{1:s}".format(self.id,self.dataVenda.strftime('%d/%m/%Y'))

    def calculaValorTotal(self):
        lista=VendaProduto.objects.filter(venda=self) # Filtra os itens vinculados a esta venda
        #total=0
        #for item in lista: # Percorre a lista de itens, calculando o valor unitário
        #    total=total + item.produto.valorUnitario * item.quantidade
        #return total

        resultado=lista.aggregate(total=models.Sum(models.F('produto__valorUnitario')*models.F('quantidade'),output_field=models.FloatField()))
        return resultado['total']

class VendaProduto(models.Model):
    venda=models.ForeignKey(Venda,on_delete=models.CASCADE)
    produto=models.ForeignKey(Produto,on_delete=models.PROTECT)
    quantidade=models.IntegerField("Quantidade")
    @property
    def subtotal(self):
        return self.produto.valorUnitario*self.quantidade

projetovendas/appvendas/views.py
from django.shortcuts import render
from django.http import HttpResponse
from appvendas.models import *
# Create your views here.

def home(request):
    return render(request,'base.html')
def exibirproduto(request,id_produto):
    produto=Produto.objects.get(id=id_produto)
    return render(request,'exibirproduto.html',{'produto':produto})
def listarprodutos(request):
    produtos=Produto.objects.all().order_by('descricao')
    lista={'produtos':produtos}
    return render(request,'produtos.html',lista)
def listarunidades(request):
    unidades=Unidade.objects.all().order_by('descricao')
    lista={'unidades':unidades}
    return render(request,'unidades.html',lista)
def exibirunidade(request,id_unidade):
    unidade=Unidade.objects.get(id=id_unidade)
    return render(request,'exibirunidade.html',{'unidade':unidade})
def listarvendas(request):
    vendas=Venda.objects.all()
    lista={'vendas':vendas}
    return render(request,'vendas.html',lista)

projetovendas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sistema de Vendas</title>
    <style>
        table, th, td {
            border: 1px solid black;
        }
    </style>
</head>
<body>
    <h2>Sistema de Vendas</h2>
    <nav>
        <a href="{% url 'unidades' %}"> Unidades </a>
        <a href="#"> Cargos</a>
        <a href="{% url 'produtos' %}"> Produtos</a>
        <a href="#"> Clientes</a>
        <a href="#"> Funcionários</a>
        <a href="{% url 'vendas' %}"> Vendas</a>
        <a href="#"> Cadastros</a>
    </nav>
    {% block conteudo %}
        <h3>Bem vindo ao sistema de controle de vendas</h3>
    {% endblock %}
</body>
</html>

projetovendas/templates/exibirproduto.html
{% extends 'base.html' %}
{% block conteudo %}

    <h2>Dados do Produto</h2>
    <ul>
    <li>Descrição: {{ produto.descricao|upper }}</li>
     <li>Unidade: {{ produto.unidade.sigla|upper }}</li>
    <li>Valor Unitário: {{ produto.valorUnitario|floatformat:2 }}</li>
    </ul>
{% endblock %}

projetovendas/templates/exibirunidade.html
{% extends 'base.html' %}
{% block conteudo %}
    <h2>Dados da Unidade </h2>
    <ul>
    <li>Descrição: {{ unidade.descricao }}</li>
    <li>Sigla : {{ unidade.sigla }}</li>
    </ul>

{% endblock %}

projetovendas/templates/produtos.html
{% extends 'base.html' %}
{% block conteudo %}
    <h2>Produtos</h2>
<table>
  <tr>
    <th>Descrição</th>
    <th>Unidade</th>
      <th>Valor Unitário</th>
  </tr>
    {% for produto in produtos %}
        <tr>
            <td><a href="{% url 'exibirproduto' produto.id %}"> {{ produto.descricao | upper }}</a></td>
            <td>{{ produto.unidade.sigla }}</td>
            <td>{{ produto.valorUnitario | floatformat:2 }}</td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

projetovendas/templates/unidades.html
{% extends 'base.html' %}
{% block conteudo %}
    <h2>Unidades</h2>
    <table>
  <tr>
    <th>Descrição</th>
    <th>Sigla</th>
  </tr>
    {% for unidade in unidades %}
        <tr>
            <td><a href="{% url 'exibirunidade' unidade.id %}"> {{ unidade.descricao | upper }}</a></td>
            <td>{{ unidade.sigla }}</td>
        </tr>
    {% endfor %}

</table>
{% endblock %}

projetovendas/templates/vendas.html
{% extends 'base.html' %}

{% block conteudo %}
    <h2>Vendas</h2>

    {% for venda in vendas %}
        <ul>
        <li><h3>Venda - {{ venda.id }}</h3></li>
        <li>Cliente: {{ venda.cliente.nome }}</li>
        <li>Funcionário: {{ venda.vendedor.nome }}</li>
        <li>Data da Venda {{ venda.dataVenda|date:'d/m/Y'  }}</li>
        </ul>
        <h4>Itens</h4>
        <table>
          <tr>
            <th>Descrição</th>
            <th>Unidade</th>
              <th>Quantidade</th>
              <th>Valor Unitário</th>
              <th>Subtotal</th>
          </tr>
            {% for item in venda.vendaproduto_set.all %}
               <tr>
               <td>{{ item.produto.descricao }}</td>
                <td>{{ item.produto.unidade.descricao }}</td>
               <td>{{ item.quantidade }}</td>
               <td>{{ item.produto.valorUnitario }}</td>
               <td>{{item.subtotal }}</td>
               </tr>
            {% endfor %}
        </table>
    {% endfor %}


{% endblock %}